name: Generate Weights & Biases Report
description: Generate a Weights & Biases Report automatically via a template.  See readme for details.
branding:
  icon: book-open
  color: yellow
inputs:
  wandb_api_key:
    description: Your wandb API key available at `/authorize`.  We recommend setting this in github secrets!
    required: true
runs:
  using: composite
  steps:
  - name: Checkout Repo
    uses: actions/checkout@v3
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'
      cache: 'pip'
  - name: Install wandb
    run: pip install -r requirements.txt
    shell: bash
  - name: Generate a new report
    id: generate-report
    run: |
      report_url=$(python make_report.py)
      echo "REPORT_URL=$report_url" >> $GITHUB_OUTPUT
    shell: bash
    env:
      WANDB_API_KEY: ${{ inputs.wandb_api_key }}
  - name: Echo Output
    run: |
      echo "Generated report at ${{ steps.generate-report.outputs.REPORT_URL }}"
      echo "Generated report at ${{ steps.generate-report.outputs.REPORT_URL }}" >> $GITHUB_STEP_SUMMARY
    shell: bash
